### PR TITLE
Add Creatures

### PR DESCRIPTION
**Pull request by marktoda**
Adds new tile type "Creature" denoted in maps by an "x" which
run around through empty space and generally cause havoc. Right now they
don't cause any direct damage to the player, though they make it really
easy to get stuck in spots. If we decide this is too annoying, we can
add Player to the list of tiles that these creatures bounce off of --
that'll make it so the player doesn't get stuck as much. Also adds
a map, "02", which highlights these new characters. It's probably too
chaotic but kind of fun for now. It's loosely based off one I saw in
a boulder dash YT video.

Peek 2020-05-10 10-44

### CODE REVIEW

**Comment by marktoda** [comment]
I think the `Creature` struct enum is a little awkward. I tried to have a trait that tile objects all have to implement (that way creature could just be a struct implementing that tile trait), but that got awkward in its own way. Shortcomings in my rust experience -- I'd love suggestions on a cleaner way to do it

**Comment by dpc** [comment]
`trait`s are generally best for "open ended sets", that external users of the code are supposed to implement themselves. `enum`s are best if a set is fixed and known and it's more important to more rigurously consider every case. I think in a game like this `enum`s are a better approach. Otherwise you have to spend a lot of time inventing and modifying  abstractions that a given trait must have, which are getting more and more gnarly in things like games.

**Comment by dpc** [comment]
BTW. Do you know that you can zoom in and out with `+` and `-`? The sprites of the scores are getting a bit in a way now. I'm not sure what's the best way to achive this now. Probably the map should just be rendered in a sub-window of some kind.

BTW. In the original game the criters follow predictable patterns following walls, either on their right or left side (depends on the creature).

If you need faster response or something, just ping me on matrix. :)

**Comment by marktoda** [comment]
> Do you know that you can zoom in and out with + and -

actually didn't know that. We can disable them for now if you like, I'll need to think on how to do it better

**Comment by dpc** [comment]
I wouldn't worry too much about it right now. :) . I actually don't know what's the right fix myself. I've asked here: https://community.amethyst.rs/t/clipping-subview/1476

**Pull request merged**
